# Add 'frontend' label to any changes in 'src/renderer' or 'web'
frontend:
  - changed-files:
    - any-glob-to-any-file: ['src/renderer/**/*', 'web/**/*']

# Add 'backend' label to any changes in 'src/main' or 'src/ipc'
backend:
  - changed-files:
    - any-glob-to-any-file: ['src/main/**/*', 'src/ipc/**/*']

# Add 'workspace' label to any changes in '.vscode' or '.cursor'
workspace:
  - changed-files:
    - any-glob-to-any-file: ['.vscode/**/*', '.cursor/**/*']

# Add 'cicd' label to any changes in '.github/workflows'
cicd:
  - changed-files:
    - any-glob-to-any-file: ['.github/workflows/**/*']

# Add 'documentation' label to any changes in md files
documentation:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md']

# Add 'dependencies' label to any changes in lock files
dependencies:
  - changed-files:
    - any-glob-to-any-file: ['package-lock.json', 'package.json']

# Add 'database' label to any changes in database files
database:
  - changed-files:
    - any-glob-to-any-file: ['drizzle/**/*', 'src/db/**/*', '**/*.sql']

# Add 'testing' label to any changes in test files
testing:
  - changed-files:
    - any-glob-to-any-file: ['**/*.test.ts', '**/*.test.tsx', '**/*.spec.ts', 'e2e-tests/**/*', 'vitest.config.ts', 'playwright.config.ts']

# Add 'configuration' label to any changes in config files
configuration:
  - changed-files:
    - any-glob-to-any-file: ['*.config.*', '*.json', '.eslintrc.*', '.prettierrc*', 'tsconfig.*.json']

# Add 'mobile' label to any changes in mobile/android
mobile:
  - changed-files:
    - any-glob-to-any-file: ['android/**/*', 'capacitor.config.ts', '*.mobile.*']

# Add 'templates' label to any changes in templates
templates:
  - changed-files:
    - any-glob-to-any-file: ['community-templates/**/*', 'advanced-templates/**/*']

# Add 'security' label to any changes in security-related files
security:
  - changed-files:
    - any-glob-to-any-file: ['SECURITY.md', '.github/workflows/codeql.yml', '.github/workflows/security*.yml']
