#!/usr/bin/env node

/**
 * Automated Installation Script for Next.js Official Template
 * Handles complete setup including dependencies, environment, and initial configuration
 */

const { execSync, spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

class NextJSInstaller {
  constructor() {
    this.projectRoot = path.resolve(__dirname, '..');
    this.packageManager = this.detectPackageManager();
  }

  detectPackageManager() {
    if (fs.existsSync(path.join(this.projectRoot, 'yarn.lock'))) return 'yarn';
    if (fs.existsSync(path.join(this.projectRoot, 'pnpm-lock.yaml'))) return 'pnpm';
    return 'npm';
  }

  async install() {
    console.clear();
    console.log('⚛️ Next.js Official Template - Automated Installation');
    console.log('=================================================\n');

    try {
      await this.showWelcome();
      await this.checkPrerequisites();
      await this.installDependencies();
      await this.setupEnvironment();
      await this.createConfiguration();
      await this.showCompletion();

    } catch (error) {
      console.error('\n❌ Installation failed:', error.message);
      console.log('\n🔧 Troubleshooting:');
      console.log('1. Make sure Node.js 18+ is installed');
      console.log('2. Check your internet connection');
      console.log('3. Try running: npm cache clean --force');
      console.log('4. Then run: npm run install-template');
      process.exit(1);
    }
  }

  async showWelcome() {
    console.log('✨ Welcome to Next.js Official Template Setup!');
    console.log('This automated installer will:');
    console.log('  📦 Install all Next.js dependencies');
    console.log('  ⚙️  Configure environment variables');
    console.log('  🛠️  Setup development configuration');
    console.log('  🎯 Prepare for full-stack development\n');

    const answer = await this.askQuestion('Ready to begin installation? (Y/n): ');
    if (answer.toLowerCase() === 'n' || answer.toLowerCase() === 'no') {
      console.log('Installation cancelled.');
      process.exit(0);
    }
  }

  async checkPrerequisites() {
    console.log('🔍 Checking prerequisites...\n');

    const nodeVersion = process.version;
    const majorVersion = parseInt(nodeVersion.slice(1).split('.')[0]);
    if (majorVersion < 18) {
      throw new Error(`Node.js version ${nodeVersion} is not supported. Please upgrade to Node.js 18 or higher.`);
    }
    console.log(`✅ Node.js ${nodeVersion}`);

    try {
      const pmVersion = execSync(`${this.packageManager} --version`, { encoding: 'utf8' }).trim();
      console.log(`✅ ${this.packageManager} ${pmVersion}`);
    } catch (error) {
      throw new Error(`${this.packageManager} is not installed or not in PATH.`);
    }

    console.log('');
  }

  async installDependencies() {
    console.log('📦 Installing Next.js dependencies...\n');

    const installCommand = this.packageManager === 'yarn' ? 'yarn install' :
                          this.packageManager === 'pnpm' ? 'pnpm install' : 'npm install';

    console.log(`Running: ${installCommand}`);

    try {
      execSync(installCommand, {
        cwd: this.projectRoot,
        stdio: 'inherit',
        env: { ...process.env, FORCE_COLOR: '1' }
      });
      console.log('\n✅ Dependencies installed successfully!\n');
    } catch (error) {
      throw new Error('Failed to install dependencies. Check your internet connection and try again.');
    }
  }

  async setupEnvironment() {
    console.log('⚙️  Setting up environment...\n');

    const envPath = path.join(this.projectRoot, '.env.local');

    if (!fs.existsSync(envPath)) {
      const envContent = `# Next.js Official Template Environment Variables
# This file was automatically generated by the install script

# Application Configuration
NEXT_PUBLIC_APP_NAME="Next.js Official Template"
NEXT_PUBLIC_APP_VERSION="1.0.0"
NEXT_PUBLIC_APP_ENV="development"

# Next.js Configuration
NEXTAUTH_SECRET="${this.generateSecret()}"
NEXTAUTH_URL="http://localhost:3000"

# Database (if using a database)
# DATABASE_URL="your-database-url-here"

# API Keys (add your own)
# NEXT_PUBLIC_API_KEY=""
# STRIPE_PUBLIC_KEY=""
# STRIPE_SECRET_KEY=""

# Development
NODE_ENV="development"
`;

      fs.writeFileSync(envPath, envContent);
      console.log('✅ Created .env.local with default configuration');
    } else {
      console.log('ℹ️  .env.local already exists - skipping creation');
    }

    console.log('');
  }

  async createConfiguration() {
    console.log('🛠️  Creating configuration files...\n');

    // Create VS Code settings
    const vscodePath = path.join(this.projectRoot, '.vscode');
    if (!fs.existsSync(vscodePath)) {
      fs.mkdirSync(vscodePath);

      const settings = {
        "typescript.preferences.importModuleSpecifier": "relative",
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.codeActionsOnSave": {
          "source.fixAll.eslint": "explicit"
        }
      };

      fs.writeFileSync(path.join(vscodePath, 'settings.json'), JSON.stringify(settings, null, 2));
      console.log('✅ Created VS Code workspace settings');
    }

    console.log('');
  }

  async showCompletion() {
    console.clear();
    console.log('🎉 Next.js Installation Complete!');
    console.log('================================\n');

    console.log('✅ All Next.js dependencies installed');
    console.log('✅ Environment configured');
    console.log('✅ Development tools ready\n');

    console.log('🚀 Ready to start developing!\n');

    console.log('📋 Available Commands:');
    console.log('  npm run dev          # Start development server');
    console.log('  npm run build        # Build for production');
    console.log('  npm run start        # Start production server');
    console.log('  npm run lint         # Run ESLint');
    console.log('  npm run type-check   # TypeScript type checking');
    console.log('');

    console.log('🌐 Development Server:');
    console.log('  Run: npm run dev');
    console.log('  Open: http://localhost:3000\n');

    console.log('📚 Features Available:');
    console.log('  ⚛️ Next.js 14 with App Router');
    console.log('  🎨 Shadcn/UI Components');
    console.log('  💨 Tailwind CSS');
    console.log('  🔷 Full TypeScript Support');
    console.log('  📱 Mobile-Responsive Design\n');

    const startNow = await this.askQuestion('Would you like to start the development server now? (Y/n): ');
    if (startNow.toLowerCase() !== 'n' && startNow.toLowerCase() !== 'no') {
      console.log('\n🚀 Starting Next.js development server...\n');
      const devProcess = spawn(this.packageManager, ['run', 'dev'], {
        cwd: this.projectRoot,
        stdio: 'inherit',
        env: { ...process.env, FORCE_COLOR: '1' }
      });

      process.on('SIGINT', () => {
        devProcess.kill('SIGINT');
        console.log('\n👋 Development server stopped. Happy coding!');
        process.exit(0);
      });
    } else {
      console.log('\n💡 To start developing later, run: npm run dev');
      console.log('📖 Check README.md for more information');
      console.log('\n🎊 Installation successful! Happy coding with Next.js Official Template! 🚀\n');
    }
  }

  generateSecret() {
    return require('crypto').randomBytes(32).toString('hex');
  }

  askQuestion(question) {
    return new Promise((resolve) => {
      const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
      });

      rl.question(question, (answer) => {
        rl.close();
        resolve(answer || 'y');
      });
    });
  }
}

// Run the installer
if (require.main === module) {
  const installer = new NextJSInstaller();
  installer.install().catch(console.error);
}

module.exports = NextJSInstaller;
