#!/usr/bin/env node

/**
 * Automated Installation Script for React Official Template
 * Handles complete setup including dependencies, environment, and initial configuration
 */

const { execSync, spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

class AutoInstaller {
  constructor() {
    this.projectRoot = path.resolve(__dirname, '..');
    this.isWindows = process.platform === 'win32';
    this.packageManager = this.detectPackageManager();
  }

  detectPackageManager() {
    // Check for lock files to determine package manager
    if (fs.existsSync(path.join(this.projectRoot, 'yarn.lock'))) return 'yarn';
    if (fs.existsSync(path.join(this.projectRoot, 'pnpm-lock.yaml'))) return 'pnpm';
    if (fs.existsSync(path.join(this.projectRoot, 'package-lock.json'))) return 'npm';
    return 'npm'; // Default to npm
  }

  async install() {
    console.clear();
    console.log('🚀 React Official Template - Automated Installation');
    console.log('================================================\n');

    try {
      await this.showWelcome();
      await this.checkPrerequisites();
      await this.installDependencies();
      await this.setupEnvironment();
      await this.createConfiguration();
      await this.setupDevelopmentTools();
      await this.showCompletion();

    } catch (error) {
      console.error('\n❌ Installation failed:', error.message);
      console.log('\n🔧 Troubleshooting:');
      console.log('1. Make sure Node.js 18+ is installed');
      console.log('2. Check your internet connection');
      console.log('3. Try running: npm cache clean --force');
      console.log('4. Then run: npm run install-template');
      process.exit(1);
    }
  }

  async showWelcome() {
    console.log('✨ Welcome to React Official Template Setup!');
    console.log('This automated installer will:');
    console.log('  📦 Install all dependencies');
    console.log('  ⚙️  Configure environment variables');
    console.log('  🛠️  Setup development tools');
    console.log('  🎯 Prepare for development\n');

    const answer = await this.askQuestion('Ready to begin installation? (Y/n): ');
    if (answer.toLowerCase() === 'n' || answer.toLowerCase() === 'no') {
      console.log('Installation cancelled.');
      process.exit(0);
    }
  }

  async checkPrerequisites() {
    console.log('🔍 Checking prerequisites...\n');

    // Check Node.js version
    const nodeVersion = process.version;
    const majorVersion = parseInt(nodeVersion.slice(1).split('.')[0]);
    if (majorVersion < 18) {
      throw new Error(`Node.js version ${nodeVersion} is not supported. Please upgrade to Node.js 18 or higher.`);
    }
    console.log(`✅ Node.js ${nodeVersion}`);

    // Check npm/yarn
    try {
      const pmVersion = execSync(`${this.packageManager} --version`, { encoding: 'utf8' }).trim();
      console.log(`✅ ${this.packageManager} ${pmVersion}`);
    } catch (error) {
      throw new Error(`${this.packageManager} is not installed or not in PATH.`);
    }

    // Check git
    try {
      const gitVersion = execSync('git --version', { encoding: 'utf8' }).trim();
      console.log(`✅ ${gitVersion}`);
    } catch (error) {
      console.log('⚠️  Git not found - some features may not work');
    }

    console.log('');
  }

  async installDependencies() {
    console.log('📦 Installing dependencies...\n');

    const installCommand = this.packageManager === 'yarn' ? 'yarn install' :
                          this.packageManager === 'pnpm' ? 'pnpm install' : 'npm install';

    console.log(`Running: ${installCommand}`);

    try {
      execSync(installCommand, {
        cwd: this.projectRoot,
        stdio: 'inherit',
        env: { ...process.env, FORCE_COLOR: '1' }
      });
      console.log('\n✅ Dependencies installed successfully!\n');
    } catch (error) {
      throw new Error('Failed to install dependencies. Check your internet connection and try again.');
    }
  }

  async setupEnvironment() {
    console.log('⚙️  Setting up environment...\n');

    const envPath = path.join(this.projectRoot, '.env.local');
    const envExample = `# React Official Template Environment Variables
# This file was automatically generated by the install script

# Application Configuration
VITE_APP_NAME="React Official Template"
VITE_APP_VERSION="1.0.0"
VITE_APP_ENV="development"

# Development Server
VITE_DEV_PORT="5173"
VITE_DEV_HOST="localhost"

# Feature Flags
VITE_ENABLE_SEO_AUDIT="true"
VITE_ENABLE_ACCESSIBILITY_CHECK="true"
VITE_ENABLE_PERFORMANCE_MONITOR="true"

# API Configuration (if needed)
# VITE_API_BASE_URL="http://localhost:3001"

# Analytics (optional)
# VITE_GA_TRACKING_ID=""
# VITE_MIXPANEL_TOKEN=""

# Social Media (for SEO)
VITE_APP_DESCRIPTION="A beautifully designed React template with advanced features including search, SEO audit, accessibility checker, and performance monitoring."
VITE_APP_KEYWORDS="React, TypeScript, Tailwind CSS, SEO, Accessibility, Performance, Modern Web Development"
VITE_APP_AUTHOR="Codiner"
`;

    if (!fs.existsSync(envPath)) {
      fs.writeFileSync(envPath, envExample);
      console.log('✅ Created .env.local with default configuration');
    } else {
      console.log('ℹ️  .env.local already exists - skipping creation');
    }

    // Create .env.example if it doesn't exist
    const envExamplePath = path.join(this.projectRoot, '.env.example');
    if (!fs.existsSync(envExamplePath)) {
      fs.writeFileSync(envExamplePath, envExample);
      console.log('✅ Created .env.example template');
    }

    console.log('');
  }

  async createConfiguration() {
    console.log('🛠️  Creating configuration files...\n');

    // Create vscode settings for better development experience
    const vscodePath = path.join(this.projectRoot, '.vscode');
    if (!fs.existsSync(vscodePath)) {
      fs.mkdirSync(vscodePath);

      const settings = {
        "typescript.preferences.importModuleSpecifier": "relative",
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.codeActionsOnSave": {
          "source.fixAll.eslint": "explicit"
        },
        "emmet.includeLanguages": {
          "typescript": "html",
          "typescriptreact": "html"
        }
      };

      fs.writeFileSync(path.join(vscodePath, 'settings.json'), JSON.stringify(settings, null, 2));
      console.log('✅ Created VS Code workspace settings');
    }

    // Create .prettierrc if it doesn't exist
    const prettierPath = path.join(this.projectRoot, '.prettierrc');
    if (!fs.existsSync(prettierPath)) {
      const prettierConfig = {
        semi: true,
        trailingComma: 'es5',
        singleQuote: true,
        printWidth: 80,
        tabWidth: 2,
        useTabs: false
      };
      fs.writeFileSync(prettierPath, JSON.stringify(prettierConfig, null, 2));
      console.log('✅ Created Prettier configuration');
    }

    console.log('');
  }

  async setupDevelopmentTools() {
    console.log('🎯 Setting up development tools...\n');

    // Build the project once to ensure everything works
    console.log('🔨 Running initial build to verify setup...');
    try {
      execSync(`${this.packageManager} run build`, {
        cwd: this.projectRoot,
        stdio: 'pipe' // Suppress output for cleaner display
      });
      console.log('✅ Build completed successfully');
    } catch (error) {
      console.log('⚠️  Build failed, but this is normal for first setup. Run "npm run dev" to start development.');
    }

    // Check if TypeScript compiles
    console.log('🔷 Checking TypeScript compilation...');
    try {
      execSync(`${this.packageManager} run type-check`, {
        cwd: this.projectRoot,
        stdio: 'pipe'
      });
      console.log('✅ TypeScript compilation successful');
    } catch (error) {
      console.log('⚠️  TypeScript errors found - run "npm run type-check" to see details');
    }

    console.log('');
  }

  async showCompletion() {
    console.clear();
    console.log('🎉 Installation Complete!');
    console.log('========================\n');

    console.log('✅ All dependencies installed');
    console.log('✅ Environment configured');
    console.log('✅ Development tools ready');
    console.log('✅ TypeScript compilation verified\n');

    console.log('🚀 Ready to start developing!\n');

    console.log('📋 Available Commands:');
    console.log('  npm run dev          # Start development server');
    console.log('  npm run build        # Build for production');
    console.log('  npm run seo-audit    # Run SEO analysis');
    console.log('  npm run accessibility-check # Check accessibility');
    console.log('  npm run performance-test    # Performance analysis');
    console.log('');

    console.log('🌐 Development Server:');
    console.log('  Run: npm run dev');
    console.log('  Open: http://localhost:5173\n');

    console.log('📚 Features Available:');
    console.log('  🔍 Advanced Search & Filtering');
    console.log('  📊 SEO Audit Tools');
    console.log('  ♿ Accessibility Checker');
    console.log('  ⚡ Performance Monitor');
    console.log('  🎨 Beautiful UI Components');
    console.log('  📱 Mobile-Responsive Design\n');

    const startNow = await this.askQuestion('Would you like to start the development server now? (Y/n): ');
    if (startNow.toLowerCase() !== 'n' && startNow.toLowerCase() !== 'no') {
      console.log('\n🚀 Starting development server...\n');
      const devProcess = spawn(this.packageManager, ['run', 'dev'], {
        cwd: this.projectRoot,
        stdio: 'inherit',
        env: { ...process.env, FORCE_COLOR: '1' }
      });

      // Handle process termination
      process.on('SIGINT', () => {
        devProcess.kill('SIGINT');
        console.log('\n👋 Development server stopped. Happy coding!');
        process.exit(0);
      });

      devProcess.on('close', (code) => {
        if (code === 0) {
          console.log('\n👋 Development server stopped. Happy coding!');
        } else {
          console.log(`\n⚠️  Development server exited with code ${code}`);
        }
        process.exit(code);
      });
    } else {
      console.log('\n💡 To start developing later, run: npm run dev');
      console.log('📖 Check README.md for more information');
      console.log('\n🎊 Installation successful! Happy coding with React Official Template! 🚀\n');
    }
  }

  askQuestion(question) {
    return new Promise((resolve) => {
      const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
      });

      rl.question(question, (answer) => {
        rl.close();
        resolve(answer || 'y'); // Default to 'y' if empty
      });
    });
  }
}

// Run the installer
if (require.main === module) {
  const installer = new AutoInstaller();
  installer.install().catch(console.error);
}

module.exports = AutoInstaller;
