"use client";

import { motion } from "framer-motion";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsPage() {
    return (
        <main className="min-h-screen bg-background text-foreground transition-colors duration-300">
            <Navbar />

            <section className="relative pt-32 pb-20">
                <div className="container mx-auto px-6">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="max-w-4xl mx-auto"
                    >
                        <h1 className="text-5xl font-bold mb-8">Terms of <span className="text-gradient">Service</span></h1>

                        <div className="space-y-12">
                            <section>
                                <p className="text-xl text-muted-foreground mb-8">
                                    By using Codiner, you agree to the following terms and conditions.
                                </p>
                            </section>

                            <div className="grid gap-8">
                                <motion.div
                                    initial={{ opacity: 0, x: -20 }}
                                    whileInView={{ opacity: 1, x: 0 }}
                                    viewport={{ once: true }}
                                    className="p-8 rounded-xl border border-border bg-card/50 backdrop-blur-sm"
                                >
                                    <h2 className="text-2xl font-bold mb-4">1. Description of Service</h2>
                                    <p className="text-muted-foreground leading-relaxed">
                                        Codiner is a desktop-native application for AI-assisted software development. We provide tools and interfaces to help you build, test, and deploy applications using artificial intelligence.
                                    </p>
                                </motion.div>

                                <motion.div
                                    initial={{ opacity: 0, x: -20 }}
                                    whileInView={{ opacity: 1, x: 0 }}
                                    viewport={{ once: true }}
                                    transition={{ delay: 0.1 }}
                                    className="p-8 rounded-xl border border-border bg-card/50 backdrop-blur-sm"
                                >
                                    <h2 className="text-2xl font-bold mb-4">2. No Warranty</h2>
                                    <p className="text-muted-foreground leading-relaxed">
                                        The application is provided "as is" without warranty of any kind, express or implied. Use of the software is at your own risk. We do not guarantee that the generated code will be error-free or suitable for any specific purpose.
                                    </p>
                                </motion.div>

                                <motion.div
                                    initial={{ opacity: 0, x: -20 }}
                                    whileInView={{ opacity: 1, x: 0 }}
                                    viewport={{ once: true }}
                                    transition={{ delay: 0.2 }}
                                    className="p-8 rounded-xl border border-border bg-card/50 backdrop-blur-sm"
                                >
                                    <h2 className="text-2xl font-bold mb-4">3. Local Responsibility</h2>
                                    <p className="text-muted-foreground leading-relaxed">
                                        You are responsible for the code generated by the AI and for the maintenance of your local environment. This includes security, backups, and verification of any AI-generated code before deployment.
                                    </p>
                                </motion.div>

                                <motion.div
                                    initial={{ opacity: 0, x: -20 }}
                                    whileInView={{ opacity: 1, x: 0 }}
                                    viewport={{ once: true }}
                                    transition={{ delay: 0.3 }}
                                    className="p-8 rounded-xl border border-primary/20 bg-card/50 backdrop-blur-sm"
                                >
                                    <h2 className="text-2xl font-bold mb-4">4. Open Source</h2>
                                    <p className="text-muted-foreground leading-relaxed">
                                        Codiner is licensed under the MIT License. You are free to modify and distribute the software in accordance with that license. The open-source nature of the project means you have full transparency and control over your development tools.
                                    </p>
                                </motion.div>
                            </div>

                            <motion.p
                                initial={{ opacity: 0 }}
                                whileInView={{ opacity: 1 }}
                                viewport={{ once: true }}
                                className="text-center text-muted-foreground pt-8"
                            >
                                Last updated: February 14, 2026
                            </motion.p>
                        </div>
                    </motion.div>
                </div>
            </section>

            <Footer />
        </main>
    );
}
